// MERN/Week_3/Day_2/Practice/books 3/client/src/Views/home.jsx
import React, { useEffect, useState } from 'react'
import axios from "axios" 
import {Link } from "react-router-dom"
import Navbar from '../components/navbar'
const home = () => {
    const [books,setBooks]=useState([])
    useEffect(()=>{
        axios.get("http://localhost:5000/api/books/")
        .then((res)=>{
            console.log(res.data)
            setBooks(res.data)
        })
        .catch((err)=>console.error(err))
    },[])
    return (
    <div>
    <Navbar title="Book Catalog"/>
    <div className='container mt-4'>

    <table className="table table-striped">
    <thead>
        <tr>
        <th scope="col">Title</th>
        <th scope="col">Author</th>
        <th scope="col">Page count</th>
        <th scope="col">Availble</th>
        <th scope="col">Book Pages</th>
        </tr>
    </thead>
    <tbody>
        {
            books.map((book)=>{
                
                return<tr key={book._id}>
        <th scope="row">{book.title}</th>
        <td>{book.author}</td>
        <td>{book.pages}</td>
        <td>{book.isAvailable ? <>Yes</> : <>No</>} | <Link to={"/update/"+book._id}>edit</Link></td>
        <td> <Link to={"/books/"+ book._id +"/details"} className='btn btn-success'>Book Details</Link> </td>
        </tr>
        })
    }
    </tbody>
    </table>
    </div>
    </div>
    )
}

export default home

// Angular/Day 2/client/src/app/home/home.component.ts
import { Component } from '@angular/core';
import { ApiService } from '../api.service';
import { CommonModule } from '@angular/common';
import { NavbarComponent } from "../navbar/navbar.component";
import { RouterModule } from '@angular/router';
import { Books } from '../books';

@Component({
  selector: 'app-home',
  imports: [CommonModule, NavbarComponent,RouterModule],
  templateUrl: './home.component.html',
  styleUrl: './home.component.css'
})
export class HomeComponent {
  title:string="Book Catalog"
  books:Books[]=[]
  constructor(private apiService:ApiService){}
  ngOnInit(): void {
    this.apiService.getAll().subscribe({
      next:data=>{
        this.books=data
      }
    })
  }
}

<app-navbar [title]="title"></app-navbar>
<div class="container">
    <table *ngIf="books.length" class="table table-striped mt-5">
        <thead>
        <tr>
            <th scope="col">Title</th>
            <th scope="col">Author</th>
            <th scope="col">Page Count</th>
            <th scope="col">Available</th>
            <th scope="col">Book Page</th>
        </tr>
        </thead>
        <tbody>
        <tr *ngFor="let book of books">
            <td>{{ book.title }}</td>
            <td>{{ book.author }}</td>
            <td>{{ book.pages }}</td>
            <td>{{ book.isAvailable ? 'Yes' : 'No' }}</td>
            <td><a routerLink="/book/{{ book._id }}" class="btn btn-success">Book Details</a></td>
        </tr>
        </tbody>
    </table>
</div>
