// Angular/Day 2/client/src/app/navbar/navbar.component.ts
import { Component, Input } from '@angular/core';
import { RouterModule } from '@angular/router';

@Component({
  selector: 'app-navbar',
  imports: [RouterModule],
  templateUrl: './navbar.component.html',
  styleUrl: './navbar.component.css'
})
export class NavbarComponent {
  @Input() title!: string;

}

<nav class="navbar navbar-expand-xl navbar-light" style="background-color: #bec2c5;">
    <div class="buttons">
        <a routerLink="/" class="btn btn-primary">Catalog</a>
        <a routerLink="/new/book" class="btn btn-primary">add Book</a>
    </div>
    <h3>{{title}}</h3>
</nav>

// MERN/Week_2/Day_5/Core/books 2/client/src/components/navbar.jsx
import React from 'react'
import {Link } from "react-router-dom"
const navbar = (props) => {
    const {title} = props;
    
    return (
    <div className='navbar'>
        <div className='buttons'>
        <Link to='/'  className='btn btn-primary button'> Catalog </Link>
        <Link to='/create' className='btn btn-primary button'> Add Book </Link></div>
        <h1 className='title'>{title}</h1>
    </div>
    )
}

export default navbar
